version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - aivascu
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - ">= 16.5.a, < 16.6"
  - dependency-name: AutoFixture.Xunit2
    versions:
    - 4.15.0
    - 4.16.0
  - dependency-name: AutoFixture.Idioms
    versions:
    - 4.15.0
    - 4.16.0
  - dependency-name: AutoFixture
    versions:
    - 4.13.0
    - 4.15.0
    - 4.16.0
  - dependency-name: AutoFixture.AutoMoq
    versions:
    - 4.15.0
    - 4.16.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
  - dependency-name: Moq
    versions:
    - 4.16.0
