variables: { DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true', DOTNET_CLI_TELEMETRY_OPTOUT: 'true' }
name: 'CI Pipeline'

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: Cake@0
  displayName: 'Build & Test'
  inputs:
    script: 'build.cake'
    target: 'Test'
    verbosity: 'Normal'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish coverage results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coverage/*.xml'
    reportDirectory: 'coverage'