name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - run: |
          git fetch --tags
          git branch --create-reflog master origin/master
        shell: powershell
      
      - name: Test Project
        run: .\build.ps1 -t Test -Verbosity Diagnostic
        shell: powershell
