name: 'Pull Request CI'

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'readme'
      - 'license'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Fetch tags and create reflog
        run: |
          git fetch --tags
          git branch --create-reflog master origin/master
        shell: powershell

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - name: Generate lcov report
        id: build
        run: .\build.ps1 --target='test:coverage' --reportTypes='lcov' --reportDir='coverage'
        shell: powershell

      - name: Display version
        run: Write-Host $env:build_version
        shell: powershell
        env:
          build_version: ${{ steps.build.outputs.version }}

      - name: Publish test coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}